### ISSUE TITLE
Touch Input nodes repeatedly fail to init

### ISSUE THREAD

**Issue by vitorio** [cyberflohr/node-red-contrib-rainbow-hat#1]
I appreciate you developing this Node-RED module!  But, I am having some trouble using it reliably.

When using a Touch Input node, I can successfully deploy it once, but any changes in my flow will cause it to fail to initialize on any re-deployment.  The error in the log looks like:

`16 Feb 07:48:55 - [error] [rainbow-hat-touch-input:ebcd24a0.c5a83] Touch input initialization failed for channel #21: {"errno":-22,"code":"EINVAL","syscall":"write"}`

When I am trying to use all three Touch Input nodes in a single flow, 1-2 of them will always fail to initialize.

Sometimes, Node-RED reports the deployment was successful, and I will only learn that it wasn't when looking at the log.  It does not always report "not connected" under the failed Touch Inputs.

**Comment by cyberflohr** [comment]
Thank you for your feedback!

I've analysed the problem and changed the code. 
Checkout new version 0.1.2

**Comment by vitorio** [comment]
This seems much better!  I have deployed and re-deployed all three Touch Input nodes without errors in the log, and the buttons seem to work reliably.  Thanks!

**Comment by cyberflohr** [comment]
Thank you for re-testing!
I'll close the issue.
